name: Build Android APK

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}

      - name: Install Android SDK command-line tools and required packages
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest || true
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

          # detect compileSdk from app module if present, fallback to 33
          if [ -f app/build.gradle.kts ]; then
            COMPILE_SDK=$(grep -Eo "compileSdk(Version)?\s*=\s*[0-9]+" app/build.gradle.kts | grep -Eo "[0-9]+" | head -1)
          elif [ -f app/build.gradle ]; then
            COMPILE_SDK=$(grep -Eo "compileSdk\s+[0-9]+" app/build.gradle | grep -Eo "[0-9]+" | head -1)
          else
            COMPILE_SDK="33"
          fi
          if [ -z "$COMPILE_SDK" ]; then
            COMPILE_SDK="33"
          fi
          echo "Detected compileSdk: $COMPILE_SDK"

          yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-$COMPILE_SDK" "build-tools;33.0.2"
          yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses || true
        shell: bash

      - name: Install Gradle 8.5 (if no gradlew)
        run: |
          if [ ! -f ./gradlew ]; then
            echo "Gradle wrapper not found: installing standalone Gradle 8.5"
            mkdir -p $HOME/gradle
            wget -q https://services.gradle.org/distributions/gradle-8.5-bin.zip -O /tmp/gradle.zip
            unzip -q /tmp/gradle.zip -d $HOME/gradle
            export PATH=$HOME/gradle/gradle-8.5/bin:$PATH
            echo "Standalone Gradle installed"
          else
            echo "Gradle wrapper found; will use ./gradlew"
          fi
        shell: bash

      - name: Ensure Gradle wrapper is executable
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
          fi

      - name: Build Debug APK
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew clean assembleDebug --no-daemon
          else
            $HOME/gradle/gradle-8.5/bin/gradle clean assembleDebug --no-daemon
          fi
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/**/*.apk
